[build]
  base    = "frontend/my-app"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://lottery-5mbv.onrender.com"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200